
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/move_web?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: HJC916924
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 1000000000
      max-request-size: 2000000000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.paperfly.system.pojo,com.paperfly.admin.pojo
server:
  port: 7001
logging:
  level:
    com.paperfly.system.mapper: debug
    com.paperfly.admin.mapper: debug